"""Shared runtime support generated by Python Deployment Builder.

This file intentionally depends only on the Python standard library.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
from datetime import UTC, datetime
from pathlib import Path

STATE_FILENAME = "deployment-state.json"


class DeploymentRuntimeError(RuntimeError):
    pass


def deployment_directory() -> Path:
    return Path(__file__).resolve().parents[1]


def load_manifest() -> dict:
    path = deployment_directory() / "manifest.json"
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise DeploymentRuntimeError(f"Deployment manifest is unreadable: {exc}") from exc


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def expand_runtime_path(value: str) -> Path:
    local_app_data = os.environ.get("LOCALAPPDATA")
    if not local_app_data:
        raise DeploymentRuntimeError("LOCALAPPDATA is unavailable for this Windows user.")
    expanded = value.replace("%LOCALAPPDATA%", local_app_data)
    return Path(expanded).resolve()


def application_root(manifest: dict) -> Path:
    return expand_runtime_path(manifest["runtime_paths"]["application_root"])


def environment_path(manifest: dict) -> Path:
    return expand_runtime_path(manifest["runtime_paths"]["environment_path"])


def logs_path(manifest: dict) -> Path:
    return expand_runtime_path(manifest["runtime_paths"]["logs_path"])


def write_application_launch_failure(manifest: dict, summary: str, details: str) -> Path:
    directory = logs_path(manifest)
    directory.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(UTC)
    path = directory / f"application-launch-failure-{timestamp:%Y%m%dT%H%M%S%fZ}.log"
    content = (
        f"Timestamp: {timestamp.isoformat()}\n"
        f"Application: {manifest['application_display_name']}\n"
        f"Entry point: {manifest['entry_point_module']}:{manifest['entry_point_callable']}\n"
        f"Problem: {summary}\n\n"
        f"Details:\n{details.rstrip()}\n"
    )
    path.write_text(redact(content), encoding="utf-8")
    return path


def latest_application_launch_failure(manifest: dict) -> Path | None:
    directory = logs_path(manifest)
    try:
        return max(
            directory.glob("application-launch-failure-*.log"),
            key=lambda path: path.stat().st_mtime_ns,
        )
    except (OSError, ValueError):
        return None


def state_path(manifest: dict) -> Path:
    return expand_runtime_path(manifest["runtime_paths"]["state_path"])


def runtime_environment(manifest: dict, project_root: Path, environment: Path) -> dict[str, str]:
    result = os.environ.copy()
    for key, value in manifest["runtime_environment"].items():
        rendered = value.replace("%PROJECT_ROOT%", str(project_root))
        rendered = rendered.replace("%LOCALAPPDATA%", result.get("LOCALAPPDATA", ""))
        result[key] = rendered
    result["UV_PROJECT_ENVIRONMENT"] = str(environment)
    result["UV_NO_ENV_FILE"] = "1"
    if manifest.get("system_certs"):
        result["UV_SYSTEM_CERTS"] = "true"
    else:
        result.pop("UV_SYSTEM_CERTS", None)
    return result


def state_signature(manifest: dict, project_root: Path) -> dict[str, object]:
    return {
        "schema_version": manifest["schema_version"],
        "application_id": manifest["application_id"],
        "deployment_fingerprint": manifest["deployment_fingerprint"],
        "uv_version": manifest["uv_version"],
        "python_version": manifest["python_version"],
        "pyproject_sha256": sha256_file(project_root / "pyproject.toml"),
        "lockfile_sha256": sha256_file(project_root / "uv.lock"),
        "selected_extras_fingerprint": manifest["selected_extras_fingerprint"],
        "approved_artifact_hashes": {
            item["filename"]: item["sha256"] for item in manifest["approved_artifacts"]
        },
        "application_artifact_sha256": (
            manifest["application_artifact"]["sha256"]
            if manifest.get("application_artifact")
            else None
        ),
        "environment_path": str(environment_path(manifest)),
    }


def load_state(manifest: dict) -> dict | None:
    path = state_path(manifest) / STATE_FILENAME
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else None
    except (OSError, json.JSONDecodeError):
        return None


def stale_reasons(manifest: dict, project_root: Path) -> list[str]:
    reasons: list[str] = []
    state = load_state(manifest)
    if state is None:
        return ["successful deployment state is missing or unreadable"]
    try:
        expected = state_signature(manifest, project_root)
    except OSError as exc:
        return [f"runtime input fingerprint could not be calculated: {exc}"]
    for key, value in expected.items():
        if state.get(key) != value:
            reasons.append(f"{key} changed")
    environment = environment_path(manifest)
    for executable in ("python.exe", "pythonw.exe"):
        if not (environment / "Scripts" / executable).is_file():
            reasons.append(f"environment Scripts/{executable} is missing")
    wheel_directory = deployment_directory() / "wheels"
    for artifact in manifest["approved_artifacts"]:
        wheel = wheel_directory / artifact["filename"]
        if not wheel.is_file() or sha256_file(wheel) != artifact["sha256"]:
            reasons.append(f"approved artifact {artifact['filename']} changed")
    application_artifact = manifest.get("application_artifact")
    if application_artifact:
        wheel = deployment_directory() / "application" / application_artifact["filename"]
        if not wheel.is_file() or sha256_file(wheel) != application_artifact["sha256"]:
            reasons.append(f"application artifact {application_artifact['filename']} changed")
    return reasons


def write_state(manifest: dict, project_root: Path, verified_at: str) -> None:
    directory = state_path(manifest)
    directory.mkdir(parents=True, exist_ok=True)
    payload = {**state_signature(manifest, project_root), "verified_at": verified_at}
    destination = directory / STATE_FILENAME
    temporary = destination.with_suffix(".tmp")
    temporary.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    temporary.replace(destination)


def guarded_environment_path(manifest: dict, candidate: Path) -> Path:
    root = application_root(manifest).resolve()
    resolved = candidate.resolve()
    allowed_names = {"env", "env.previous", "env.failed"}
    if resolved.parent != root or resolved.name not in allowed_names:
        raise DeploymentRuntimeError(f"Refusing unsafe environment operation: {resolved}")
    return resolved


def safe_remove_environment(manifest: dict, candidate: Path) -> None:
    resolved = guarded_environment_path(manifest, candidate)
    if resolved.exists():
        shutil.rmtree(resolved)


def verify_runtime_inputs(manifest: dict, project_root: Path) -> None:
    checks = (
        (project_root / "pyproject.toml", manifest["pyproject_sha256"]),
        (project_root / "uv.lock", manifest["lockfile_sha256"]),
    )
    for path, expected in checks:
        if not path.is_file() or sha256_file(path) != expected:
            raise DeploymentRuntimeError(
                f"{path.name} no longer matches this deployment kit. Regenerate the kit."
            )
    bundled_hash = manifest.get("bundled_uv_sha256")
    if bundled_hash:
        bundled_uv = deployment_directory() / "bootstrap" / "uv.exe"
        if not bundled_uv.is_file() or sha256_file(bundled_uv) != bundled_hash:
            raise DeploymentRuntimeError("Bundled uv.exe is missing or changed.")
    wheels = deployment_directory() / "wheels"
    for artifact in manifest["approved_artifacts"]:
        path = wheels / artifact["filename"]
        if not path.is_file() or sha256_file(path) != artifact["sha256"]:
            raise DeploymentRuntimeError(
                f"Approved artifact is missing or changed: {artifact['filename']}"
            )
    application_artifact = manifest.get("application_artifact")
    if application_artifact:
        path = deployment_directory() / "application" / application_artifact["filename"]
        if not path.is_file() or sha256_file(path) != application_artifact["sha256"]:
            raise DeploymentRuntimeError(
                "Application artifact is missing or changed: "
                f"{application_artifact['filename']}"
            )


def redact(text: str) -> str:
    patterns = (
        re.compile(r"(?i)(authorization\s*[:=]\s*)([^\s]+)"),
        re.compile(r"(?i)((?:api[_-]?key|token|secret)\s*[:=]\s*)([^\s]+)"),
        re.compile(r"(?i)(https?://[^\s:/]+:)([^@\s]+)(@)"),
    )
    result = text
    for pattern in patterns:
        result = pattern.sub(r"\1[REDACTED]\3" if pattern.groups == 3 else r"\1[REDACTED]", result)
    return result
